import Link from "next/link";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Web tutorial",
  description: "Generated by MJ",
};

interface Post {
  id: number,
  title: string,
  author: string
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const res = await fetch("http://localhost:9999/posts")
  const posts = await res.json()

  console.log('posts', posts)

  return (
    <html>
      <body>
        <h1><Link href="/">WEB2</Link></h1>
        <ol>
          <li><Link href="/html">html</Link></li>
          <li><Link href="/css">css</Link></li>
        </ol>
        {children}
        <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update/1">Update</Link></li>
          <li><input type="button" value="delete" /></li>
        </ul>
      </body>
    </html>
  );
}
